services:
  servidor:
    container_name: servidor
    image: carlosg18docker/eng_dados:servertcp
    tty: true
    networks:
      network1:
        ipv4_address: 172.28.0.2

  cliente:
    image: carlosg18docker/eng_dados:clienttcp
    deploy:
      mode: replicated
      replicas: 3
    tty: true
    depends_on:
      - servidor
    networks:
      - network1
    command: ["172.28.0.2"]
    restart: always
  
networks:
  network1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
